### ISSUE TITLE
could not git extract on a vfat filesystem

### ISSUE THREAD

**Issue by teuben** [amanchokshi/EMBERS-Sample-Data#1]
I accidentally cloned this on a vfat filesystem. I would grab all the data, but then failed to restore the files. git then claims the command 
          git restore --source=HEAD :/
would fix it, but not until I had copied it to a proper unix (ext4 in my case) filesystem.

Not a major issue, unless you want to support this on legacy systems.

**Comment by teuben** [comment]
a casual inspection of the names didn't make it obvious to me why it failed on VFAT.

**Comment by amanchokshi** [comment]
I've never heard of the vfat filesystem. What operating system are you on? Do you think it's just the file names that may be messing things up? Most of the data is saved as binary txt files with a couple of plain text files.

**Comment by teuben** [comment]
vfat is sometimes seen on USB or external HDD's when you buy  them. Comes out of the windows world. Also NTFS now.  It's "portable" between Mac, Linux and Windows.  But they have restrictions, e.g. no case sensitive files, there is some limitations e.g. you probably can't have a directory called /C: i would think.   So something in your filenames is not 100% portable if you ever thought of using is more portable.

**Comment by teuben** [comment]
Just realized what the vfat problem was:    filenames on vfat cannot contain a :    
So, something like **2019-10-10-10:30.json** would cause an error.

**Comment by amanchokshi** [comment]
Shucks! I'll keep that in mind for the future and make sure that we have more compatible file naming when similar experiments are run again. 

Do you think I should put a note on the examples directory that there can be problems on a vfat filesystem? What operating system are you on?

**Comment by teuben** [comment]
I'm on linux, but since I ran out of space, I went to an empty looking partition on an externally mounted HDD, which I had forgotten kept in vfat since it's useful to copy files to "alien" computers sometimes.   So, overall I don't think this is a problem. If I remember, i should check if on an ntfs you can have filenames with a : in them.   If you ever suspect you may want to support windows, this would become an issue.   mac should have no issue, but I've not tried that.

**Comment by amanchokshi** [comment]
Good to know. I'll add a comment to the top of the documentation to let users know that this is an possible issue on windows or the vfat system.
